-- Insert sample tours
INSERT INTO tours (id, name, name_so, description, description_so, destination, duration_days, price, image_url, highlights, is_featured, is_active) VALUES
(
  gen_random_uuid(),
  'Dubai Adventure Package',
  'Dalxiiska Dubaiga',
  'Experience the luxury and excitement of Dubai with our 5-day adventure package. Visit the Burj Khalifa, enjoy desert safaris, and explore the gold souks.',
  'Ku raaxayso nimcada iyo xiisaha Dubaiga oo leh qorshaha 5-maalmo ee dalxiiska. Booqo Burj Khalifa, ku raaxayso dalxiiska baadiyaha, iyo baaruufso suuqa dahabka.',
  'Dubai, UAE',
  5,
  1299.00,
  'https://images.pexels.com/photos/261322/pexels-photo-261322.jpeg?auto=compress&cs=tinysrgb&w=800',
  ARRAY['Burj Khalifa visit', 'Desert safari', 'Gold souk shopping', 'Dhow cruise dinner', 'Ski Dubai'],
  true,
  true
),
(
  gen_random_uuid(),
  'Turkey Cultural Journey',
  'Dalxiiska Dhaqanka Turkiga',
  'Discover the rich history and culture of Turkey. Explore Istanbul ancient bazaars, visit Cappadocia unique landscapes, and enjoy authentic Turkish cuisine.',
  'Raadi taariikhda iyo dhaqanka Turkiga. Baaruufso Istanbul iyo wax-soo-iibsiga casriga ah, booqo Cappadocia iyo dhul-xiradleedka, iyo ku raaxayso cunto Turkiga ah.',
  'Turkey',
  7,
  1599.00,
  'https://images.pexels.com/photos/2404843/pexels-photo-2404843.jpeg?auto=compress&cs=tinysrgb&w=800',
  ARRAY['Hagia Sophia', 'Grand Bazaar', 'Hot air balloon ride', 'Ephesus ruins', 'Turkish bath experience'],
  true,
  true
),
(
  gen_random_uuid(),
  'Maldives Paradise Escape',
  'Dalxiiska Barwaaqada Maldives',
  'Relax in the stunning Maldives islands. Enjoy crystal clear waters, water sports, and luxurious overwater bungalows.',
  'Ku nasiago jasiiradaha Maldives ee aadka u quruxsan badna. Ku raaxayso biyaha wax- cadcad, ciyaaraha biyaha, iyo qolal wanaagsan oo ku yaala biyaha kor.',
  'Maldives',
  6,
  2499.00,
  'https://images.pexels.com/photos/1483055/pexels-photo-1483055.jpeg?auto=compress&cs=tinysrgb&w=800',
  ARRAY['Overwater bungalow', 'Snorkeling', 'Sunset cruise', 'Spa treatment', 'Private beach dinner'],
  true,
  true
),
(
  gen_random_uuid(),
  'Saudi Arabia Umrah Package',
  'Xajka iyo Umradaha Sucuudiga',
  'Spiritual journey to the holy cities of Makkah and Madinah. Our comprehensive package includes visas, accommodation, and guided tours.',
  'Safarka ruuxiga ah ee magaalooyinka quduska ah ee Makkah iyo Madinah. Qorshahaayadu waxay ku jirtaa fiisada, degel, iyo dalxiis xagga lataliyayaasha ah.',
  'Saudi Arabia',
  10,
  1899.00,
  'https://images.pexels.com/photos/1624656/pexels-photo-1624656.jpeg?auto=compress&cs=tinysrgb&w=800',
  ARRAY['Makkah visit', 'Madinah ziyarat', 'Hotel near Haram', 'Guided religious tours', 'Transportation included'],
  true,
  true
),
(
  gen_random_uuid(),
  'Kenya Safari Experience',
  'Dalxiiska Safari Kenya',
  'Witness the incredible wildlife of Kenya. Safari tours through Maasai Mara, luxury lodges, and authentic African experiences.',
  'La soco xayawaanka Kenya ee aad u xiisaha badan. Safari dhinac Maasai Mara, degel wanaagsan, iyo waayo-aragnimo Afrika ah.',
  'Kenya',
  8,
  1799.00,
  'https://images.pexels.com/photos/247502/pexels-photo-247502.jpeg?auto=compress&cs=tinysrgb&w=800',
  ARRAY['Maasai Mara safari', 'Luxury lodge stays', 'Big Five wildlife', 'Cultural village visit', 'Photography tours'],
  false,
  true
),
(
  gen_random_uuid(),
  'Somalia Coast & Culture',
  'Xeebta iyo Dhaqanka Soomaaliya',
  'Enjoy coastal history and modern Somali hospitality with visits to Mogadishu markets, Berbera beaches, and historic landmarks.',
  'Ku raaxayso taariikhda xeebaha iyo martida Soomaaliya ee casriga ah oo booqasho ku tago suuqyada Muqdisho, xeebaha Berbera, iyo meelo taariikhi ah.',
  'Somalia',
  6,
  1299.00,
  'https://images.pexels.com/photos/1611744/pexels-photo-1611744.jpeg?auto=compress&cs=tinysrgb&w=800',
  ARRAY['Mogadishu market tour', 'Berbera beach day', 'Historic Old City walk', 'Cultural dining', 'Local artisan market'],
  true,
  true
),
(
  gen_random_uuid(),
  'Tanzania Safari & Zanzibar',
  'Safari iyo Zanzibar Tanzania',
  'Experience a classic Tanzania safari and relax on Zanzibar beaches. Includes game drives, cultural village visits, and beach resort stays.',
  'Ku raaxayso safari caadi ah oo Tanzania ah oo ku raaxayso xeebaha Zanzibar. Waxaa ku jira safar xayawaan, booqasho tuulo dhaqameed, iyo degel xeebeed.',
  'Tanzania',
  10,
  1699.00,
  'https://images.pexels.com/photos/7026321/pexels-photo-7026321.jpeg?auto=compress&cs=tinysrgb&w=800',
  ARRAY['Serengeti safari', 'Zanzibar beach stay', 'Cultural village visit', 'Spice tour', 'Sunset dhow cruise'],
  true,
  true
),
(
  gen_random_uuid(),
  'Congo River & Wildlife',
  'Webiga Congo iyo Xayawaanka',
  'Discover the lush landscapes of the Congo with river cruises, wildlife treks, and local cultural experiences in Kinshasa and Goma.',
  'Baaro dhulka cagaaran ee Congo adigoo qaadanaya safarro webi, socdaalo xayawaan, iyo waayo-aragnimo dhaqameed oo Kinshasa iyo Goma ah.',
  'Congo',
  9,
  1499.00,
  'https://images.pexels.com/photos/3215764/pexels-photo-3215764.jpeg?auto=compress&cs=tinysrgb&w=800',
  ARRAY['River cruise', 'Wildlife treks', 'Cultural village tour', 'Kinshasa city highlights', 'Goma volcano views'],
  true,
  true
),
(
  gen_random_uuid(),
  'Zambia Victoria Falls Adventure',
  'Victoria Falls Zambia',
  'Visit Victoria Falls and enjoy Zambian wilderness adventures, river activities, and cultural experiences near Livingstone.',
  'Booqo Victoria Falls oo ku raaxayso waayo-aragnimada duurjoogta Zambia, hawlo webi, iyo dhaqanka ku dhow Livingstone.',
  'Zambia',
  8,
  1599.00,
  'https://images.pexels.com/photos/865017/pexels-photo-865017.jpeg?auto=compress&cs=tinysrgb&w=800',
  ARRAY['Victoria Falls visit', 'Zambezi river cruise', 'Livingstone village visit', 'White-water rafting', 'Safari walks'],
  true,
  true
),
(
  gen_random_uuid(),
  'Egypt Historical Tour',
  'Dalxiiska Taariikhda Masar',
  'Explore ancient Egyptian civilization. Visit the Pyramids, cruise the Nile, and discover the treasures of the pharaohs.',
  'Baaruufso dhaqanka Masar ee hore. Booqo Pyramids, Safaridii Niilka, iyo raadi dahabka firfirnaa.',
  'Egypt',
  9,
  1499.00,
  'https://images.pexels.com/photos/71241/pexels-photo-71241.jpeg?auto=compress&cs=tinysrgb&w=800',
  ARRAY['Pyramids of Giza', 'Nile cruise', 'Valley of Kings', 'Egyptian Museum', 'Abu Simbel temples'],
  false,
  true
);

-- Insert sample hotels
INSERT INTO hotels (id, name, name_so, location, description, description_so, price_per_night, rating, amenities, image_url, is_active) VALUES
(
  gen_random_uuid(),
  'Grand Hyatt Dubai',
  'Grand Hyatt Dubaiga',
  'Dubai UAE',
  'Luxury 5-star hotel in the heart of Dubai with stunning views of the skyline and world-class amenities.',
  'Hoteelka 5-geed oo raaxo leh ee ku yaala wadada Dubai oo leh aragga iyo adeeg caalami ah.',
  450.00,
  4.8,
  ARRAY['Free WiFi', 'Pool', 'Spa', 'Gym', 'Restaurant', 'Bar', 'Room Service', 'Parking'],
  'https://images.pexels.com/photos/261322/pexels-photo-261322.jpeg?auto=compress&cs=tinysrgb&w=800',
  true
),
(
  gen_random_uuid(),
  'Istanbul Palace Hotel',
  'Hoteelka Qasriga Istanbul',
  'Istanbul Turkey',
  'Historic boutique hotel near the Grand Bazaar offering traditional Turkish hospitality and modern comfort.',
  'Hoteelka taariikhiga ah oo ku dhow Grand Bazaar oo bixiya martida Turkiga iyo raaxo casriga ah.',
  280.00,
  4.6,
  ARRAY['Free WiFi', 'Breakfast', 'Restaurant', 'Concierge', 'Laundry', 'Airport Transfer'],
  'https://images.pexels.com/photos/532263/pexels-photo-532263.jpeg?auto=compress&cs=tinysrgb&w=800',
  true
),
(
  gen_random_uuid(),
  'Paradise Island Resort',
  'Degmada Jasiiradda Barwaaqada',
  'Male Maldives',
  'Exclusive overwater villa resort with private beaches, water sports center, and underwater restaurant.',
  'Qasr ku yaala biyaha oo leh xeeb gaar ah, xarunta ciyaaraha biyaha, iyo maktabada biyaha hoose.',
  890.00,
  4.9,
  ARRAY['Private Beach', 'Overwater Villa', 'Water Sports', 'Spa', 'Restaurant', 'Diving Center', 'Free WiFi'],
  'https://images.pexels.com/photos/1483055/pexels-photo-1483055.jpeg?auto=compress&cs=tinysrgb&w=800',
  true
),
(
  gen_random_uuid(),
  'Makkah Royal Clock Tower',
  'Burjaha Saacadda Makkah',
  'Makkah Saudi Arabia',
  'Premium hotel within walking distance of the Haram with direct views of the Kaaba and prayer facilities.',
  'Hoteelka wanaagsan oo qiyaastii 5 daqiiqo laga soo socdo xaramka oo leh aragga Kaaba iyo xarunta salaadda.',
  520.00,
  4.7,
  ARRAY['Haram Views', 'Prayer Room', 'Restaurant', '24/7 Room Service', 'Shuttle Service', 'Free WiFi'],
  'https://images.pexels.com/photos/1624656/pexels-photo-1624656.jpeg?auto=compress&cs=tinysrgb&w=800',
  true
),
(
  gen_random_uuid(),
  'Safari Lodge Kenya',
  'Degmada Safari Kenya',
  'Maasai Mara Kenya',
  'Eco-friendly luxury lodge in the heart of Maasai Mara with exclusive safari experiences and wildlife viewing.',
  'Degmo wanaagsan oo deegaanka ah ee ku yaala wadada Maasai Mara oo leh waayo-aragnimo safari iyo xayawaan.',
  380.00,
  4.8,
  ARRAY['Safari Tours', 'Pool', 'Restaurant', 'Bar', 'Wildlife Viewing', 'Cultural Activities', 'Free WiFi'],
  'https://images.pexels.com/photos/247502/pexels-photo-247502.jpeg?auto=compress&cs=tinysrgb&w=800',
  true
),
(
  gen_random_uuid(),
  'Nile View Hotel',
  'Hoteelka Dalxiiska Niilka',
  'Cairo Egypt',
  'Elegant hotel overlooking the Nile River with easy access to Giza Pyramids and Cairo attractions.',
  'Hoteelka wanaagsan oo ku yaala wabaka Niilka oo leh gashasho fudud ee Pyramids iyo meelaha Cairo.',
  190.00,
  4.4,
  ARRAY['Nile Views', 'Pool', 'Restaurant', 'Bar', 'Tour Desk', 'Free WiFi', 'Airport Shuttle'],
  'https://images.pexels.com/photos/71241/pexels-photo-71241.jpeg?auto=compress&cs=tinysrgb&w=800',
  true
);
